#include "cpu.h"

void ADC(uint8_t value);
void AND(uint8_t value);
void ASL(uint8_t value, uint16_t address);
void Branch(uint8_t value);
void BCC(uint8_t value);
void BCS(uint8_t value);
void BEQ(uint8_t value);
void BIT(uint8_t value);
void BMI(uint8_t value);
void BNE(uint8_t value);
void BPL(uint8_t value);
void BRK(uint8_t value);
void BVC(uint8_t value);
void BVS(uint8_t value);
void CLC(uint8_t value);
void CLD(uint8_t value);
void CLI(uint8_t value);
void CLV(uint8_t value);
void CMP(uint8_t value);
void CPX(uint8_t value);
void CPY(uint8_t value);
void DEC(uint16_t address, uint8_t value);
void DEX();
void DEY();
void EOR(uint8_t value);
void INC(uint16_t address, uint8_t value);
void INX();
void INY();
void JMP(uint16_t address);
void JSR(uint16_t address);
void LDA(uint8_t value);
void LDX(uint8_t value);
void LDY(uint8_t value);
void LSR(uint8_t value);
void NOP(uint8_t value);
void ORA(uint8_t value);
void PHA(uint8_t value);
void PHP(uint8_t value);
void PLA(uint8_t value);
void PLP(uint8_t value);
void ROL(uint8_t value);
void ROR(uint8_t value);
void RTI(uint8_t value);
void RTS(uint8_t value);
void SBC(uint8_t value);
void SEC(uint8_t value);
void SED(uint8_t value);
void SEI(uint8_t value);
void STA(uint16_t address, uint8_t value);
void STX(uint16_t address, uint8_t value);
void STY(uint16_t address, uint8_t value);
void TAX(uint8_t value);
void TAY(uint8_t value);
void TSX(uint8_t value);
void TXA(uint8_t value);
void TXS(uint8_t value);
void TYA(uint8_t value);
